---
title: "54_Ashar Kurnia_Capstone Project"
author: "ashar"
date: "2026-02-26"
output: html_document
---
# ------------------------------------------------------------------------------
# Setup
# ------------------------------------------------------------------------------
```{r}
#Install packages


if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DESeq2")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install('EnhancedVolcano')

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("ComplexHeatmap")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("fontLiberation")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("clusterProfiler")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("AnnotationDbi")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("org.Hs.eg.db")


if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("tidyverse")

BiocManager::install(update = TRUE, ask = FALSE)
```


```{r}
#Load library
library(DESeq2)
library(EnhancedVolcano)
library(ggplot2)
library(ComplexHeatmap)
library(org.Hs.eg.db)
library(AnnotationDbi)
library(fontLiberation)
library(clusterProfiler)
library(tidyverse)

```


# ------------------------------------------------------------------------------
# Download data
# ------------------------------------------------------------------------------

```{r}
# Download raw counts from EBI
counts = read.delim("https://www.ebi.ac.uk/gxa/experiments-content/E-MTAB-9479/resources/DifferentialSecondaryDataFiles.RnaSeq/raw-counts")
head(counts)

```

```{r}
# Download metadata
metadata = read.delim("https://www.ebi.ac.uk/gxa/experiments-content/E-MTAB-9479/resources/ExperimentDesignFile.RnaSeq/experiment-design")
head(metadata)
```

# ------------------------------------------------------------------------------
# Wrangle data for DESeq2
# ------------------------------------------------------------------------------



```{r}
# Counts data wrangling
# DESeq expects the counts to have gene IDs as row names
counts$Gene.ID <- as.character(counts$Gene.ID)
rownames(counts) <- counts$Gene.ID
head(counts)
```

```{r}
# Separate gene ID with gene counts
genes = counts[, c("Gene.ID", "Gene.Name"),drop=FALSE]
genes = na.omit(genes) #optional
counts = counts[, -c(1, 2)]
head(counts)

```

```{r}
#Metadata Wrangling
# DESeq expects the metadata matrix to have sample IDs in the rownames
metadata$Run <- as.character(metadata$Run)
rownames(metadata) = metadata$Run
head(metadata)
```

```{r}

# Only keep columns of interest
metadata = metadata[, c("Sample.Characteristic.stimulus."), drop=FALSE] #Drop are used to make data frame with one column
# Look at metadata to see how the variables change with respect to each other
metadata
```


```{r}
# Rename column
colnames(metadata) = "treatment"
```

```{r}
# Turn stimulus/treatment into a factor
metadata$treatment = factor(metadata$treatment, levels =c("BMP2", "PBS"))
```

# ------------------------------------------------------------------------------
# Run DESeq
# ------------------------------------------------------------------------------
```{r}
dds <- DESeqDataSetFromMatrix(countData=counts, colData=metadata, design=~treatment)

```


```{r}
# Ignore genes with low counts
dds <- dds[rowSums(counts(dds)) > 10, ]
```

```{r}
# Run DESeq
dds <- DESeq(dds)

```

```{r}
# Compare expression
res <- results(dds, contrast=c("treatment", "BMP2", "PBS"), alpha=0.05)

na.omit(res)

```
# ------------------------------------------------------------------------------
# Top 10 gene
# ------------------------------------------------------------------------------

```{r}
# Convert DESeq2 result into dataframe
res_df <- as.data.frame(res)
```

```{r}
#Top 10 Gene
#Filter pvalue and Log2FoldChange
res_df_filter <- res_df[(res_df$padj < 0.05) & (abs(res_df$log2FoldChange) > 2.5),]

res_df_filter <- na.omit(res_df)

#Ordered padj
top10_gene_ordered <- res_df_filter[order(res_df_filter$padj, res_df_filter$log2FoldChange), ]

# Top10 gene base on padj and fold2 change
top10_gene <- head(top10_gene_ordered, 10)
top10_gene_df <- as.data.frame(top10_gene)

```
# ------------------------------------------------------------------------------
# Gene Annotation
# ------------------------------------------------------------------------------


```{r}
#Add gene ID column
res_df_filter$Gene.ID <- rownames(res_df_filter)
top10_gene_df$Gene.ID <- rownames(top10_gene_df)
```

```{r}
#Annotate gene ID
res_df_filter$Gene.Names <- mapIds(org.Hs.eg.db,keys = rownames(res_df_filter), keytype = "ENSEMBL", column = "SYMBOL")

top10_gene_df$Gene.Names <- mapIds(org.Hs.eg.db,keys = rownames(top10_gene_df), keytype = "ENSEMBL", column = "SYMBOL")

```

```{r}
#Export to Excel (optional for GO and pathway enrichment)
write.csv(top10_gene_df, file="top10_gene_deseq_result.csv")
```

# ------------------------------------------------------------------------------
# Visualization
# -----------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# 1.Volcano plot
# -----------------------------------------------------------------------------

```{r}
#Set upregulated and Downregulated gene
up <- top10_gene_df[top10_gene_df$log2FoldChange > 2.5, ]
down <- top10_gene_df[top10_gene_df$log2FoldChange < 0.5, ]


```

```{r}
#Merge upregulated and downregulated gene
top10_gene_bind <- rbind(up, down)
```

```{r}
#Enhanced volcano
volcano <-  EnhancedVolcano(
  res_df_filter,
  lab = res_df_filter$Gene.Names,
  x = 'log2FoldChange',
  y = 'padj', 
  selectLab = top10_gene_bind$Gene.Names,
  title = "Top 10 Gene Expression of BMP signaling in Ovarian Cancer Gene",
  pCutoff = 0.05,
  FCcutoff = 1
)

```

```{r}
#Export result image
png("Volcano plot.png", res = 300, height = 3000, width = 3000)
print(volcano)
dev.off()
```
# ------------------------------------------------------------------------------
# 2.Heatmap
# -----------------------------------------------------------------------------


```{r}

mat <- counts(dds,normalized = T)[rownames(top10_gene_df),]

h <- Heatmap(mat, 
        cluster_rows=T,
        column_labels = colnames(mat),
        column_title = "Top 10 Gene Expression of BMP signaling in Ovarian Cancer Gene",
        name="Z-score", 
        row_labels=top10_gene_df[rownames(mat),]$Gene.Names)

```

```{r}
#Export result image
print("Heatmap.png", res = 300, height = 3000, width = 3000)
print(h)
dev.off()

```
# ------------------------------------------------------------------------------
# GO Enrichment and KEGG pathways
# -----------------------------------------------------------------------------

```{r}
#Take data to test
genes_to_test <- rownames(top10_gene_df)

```

```{r}
#GO Analysis
GO_results_BP <- enrichGO(gene = genes_to_test, OrgDb = "org.Hs.eg.db", keyType = "ENSEMBL", ont = "BP", pvalueCutoff = 0.05)
GO_results_MF <- enrichGO(gene = genes_to_test, OrgDb = "org.Hs.eg.db", keyType = "ENSEMBL", ont = "MF", pvalueCutoff = 0.05)
GO_results_CC <- enrichGO(gene = genes_to_test, OrgDb = "org.Hs.eg.db", keyType = "ENSEMBL", ont = "CC", pvalueCutoff = 0.05)

```

```{r}

#GO barplot
fit_BP <- plot(barplot(GO_results_BP, showCategory = 20))
fit_MF <- plot(barplot(GO_results_MF, showCategory = 20))
fit_CC <- plot(barplot(GO_results_CC, showCategory = 20))
```

```{r}
#Export GO barplot
png("GO barplot_BP.png", res = 250, width=1400, height = 2000)
print(fit_BP)

dev.off()

png("GO barplot_MF.png", res = 250, width=1400, height = 2000)
print(fit_MF)

dev.off()

png("GO barplot_CC.png", res = 250, width=1400, height = 2000)
print(fit_CC)

dev.off()

```

```{r}
#Save R environemnt(optional)
save.image(file = "54_Ashar Kurnia_Capstone_Project.RData")
```